image: node:14.18.0-alpine

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - yarn
    - yarn build
    - echo "Compile complete."

test-job:
  stage: test
  script:
    - echo "Testing the code..."
    - yarn test
    - echo "Testing complete."

deploy-job:
  stage: deploy
  script:
    - echo "Deploying docs..."
    - cp -r dist/. docs/dist
    - npm i -g firebase-tools
    - firebase deploy --token $FIREBASE_TOKEN
    - echo "Lynk docs successfully deployed."
  only:
    refs:
      - main
