workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "web"

stages:
  - build
  - test
  - deploy

default:
  image: node:14.18
  cache:
    paths:
      - node_modules/
      - .yarn

build-package:
  stage: build
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install
  script:
    - echo "Building the code..."
    - yarn build
  artifacts:
    paths:
      - dist/
      - src/
      - docs/
      - node_modules/

run-tests:
  stage: test
  needs:
    - build-package
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install
  script:
    - yarn test --puppeteer

deploy-docs:
  stage: deploy
  needs:
    - build-package
  before_script:
    - npm i -g firebase-tools
  script:
    - echo "Deploying the docs"
    - cp -r dist/. docs/dist
    - firebase deploy --token $FIREBASE_TOKEN
    - echo "Docs successfully deployed."
  only:
    refs:
      - main
