image: node:14.18

stages:
  - deploy

deploy-job:
  stage: deploy
  before_script:
    - npm i -g firebase-tools
  script:
    - echo "Compiling the code..."
    - yarn
    - yarn build
    - echo "Deploying the docs"
    - cp -r dist/. docs/dist
    - firebase deploy --token $FIREBASE_TOKEN
    - echo "Docs successfully deployed."
  only:
    refs:
      - main
