workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "web"

stages:
  - build
  - test
  - versioning
  - release
  - deploy

default:
  image: node:14.18
  cache:
    paths:
      - node_modules/
      - .yarn

build-package:
  stage: build
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install
  script:
    - echo "Building the code..."
    - yarn build
  artifacts:
    expire_in: 1 hour
    paths:
      - dist/
      - docs/
      - node_modules/

run-tests:
  stage: test
  image: mcr.microsoft.com/playwright:v1.28.0-focal
  parallel: 7
  before_script:
    - yarn
    - yarn build
  script:
    - npx playwright test --shard=$CI_NODE_INDEX/$CI_NODE_TOTAL

# create-release:
#   stage: release
#   image: registry.gitlab.com/gitlab-org/release-cli:latest
#   rules:
#     - if: $CI_COMMIT_TAG
#       when: never
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#   script:
#     - echo "running release_job for $TAG"
#   release:                                         # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
#     tag_name: 'v0.$CI_PIPELINE_IID'                # The version is incremented per pipeline.
#     description: 'v0.$CI_PIPELINE_IID'
#     ref: '$CI_COMMIT_SHA'

deploy-docs:
  stage: deploy
  needs:
    - job: build-package
      artifacts: true
  before_script:
    - npm i -g firebase-tools
  script:
    - echo "Deploying the docs"
    - cp -r dist/. docs/dist
    - firebase deploy --token $FIREBASE_TOKEN
    - echo "Docs successfully deployed."
  only:
    refs:
      - main
